version: '3.8'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./php:/var/www/html

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${PHP_root_password}
      MYSQL_DATABASE: ${PHP_DB_database}
      MYSQL_USER: ${PHP_DB_username}
      MYSQL_PASSWORD: ${PHP_DB_password}
